version: "3.9"

services:
  project-zomboid:
    container_name: pzserver
    image: bachrousseau/pzserver
    restart: unless-stopped
    environment:
      PZ_ADMIN_PASS: "pzadmin"
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262:16262/udp"
